### ISSUE TITLE
フロント・バックエンド担当者・技術選定決め

### ISSUE THREAD

**Issue by Rei-Suzuki1729** [nkc-ug/ujiyamada_project_2022#1]

**Comment by Rei-Suzuki1729** [comment]
フロント希望
佐竹
バックエンド希望
saimun
です。

**Comment by jesterkaz** [comment]
フロントエンド
谷山
佐竹

バックエンド
小塚
saimun

**Comment by jesterkaz** [comment]
リーダー
谷山

**Comment by Rei-Suzuki1729** [comment]
次は技術選定ですね

フロント

バックエンド

データベース

**Comment by Rei-Suzuki1729** [comment]
このリポの権限で谷山君をadminにしました。

**Comment by Iyarr** [comment]
フロントエンド　HTML,css.react
バックエンド　php
データベース　MySQL

**Comment by Rei-Suzuki1729** [comment]
- PHPはフレームワークを使う？？
- 他に使う予定の技術はある？？(可能性として)

**Comment by saimun15** [comment]
phpはlaravelフレームワークを使おうと思います。

**Comment by Rei-Suzuki1729** [comment]
> フロントエンド　HTML,css.react バックエンド　php データベース　MySQL

こちらですが、機能を全部つくるときついと思うので、検索の候補とかを出す機能を誰かが作ってたりとかするので、それも踏まえながら、使うかどうか決めるとよいですよ。

まとめサイト　[npm](https://www.npmjs.com/)
qiita,zenn等々
